### ISSUE TITLE
Define csv file output names

### ISSUE THREAD

**Issue by e2d2** [cul-it/rmc-workflow-scripts#11]
guymager log output csv name: image_info.csv
file system ID output csv name: filesystem.csv
level1 ID output csv name: level1.csv

If csv already exists, throw error.

**Comment by dd388** [comment]
New file to merge, added in https://github.com/cul-it/rmc-workflow-scripts/commit/94ed81d5194c3e1bf397916d1cf96519b59bf7f9#diff-59149acaa113e6560977d54c6d31eb55R38
