### ISSUE TITLE
Delete extraneous disk images after organize

### ISSUE THREAD

**Issue by e2d2** [cul-it/rmc-workflow-scripts#13]
After organized, delete the un-organized disk images (or just move them to folder in new place rather than copying?)

**Comment by dd388** [comment]
Alternate idea -- move everything into a to_delete folder when not needed.

**Comment by dd388** [comment]
@e2d2 -- When you run the new scripts, can we go over this part again? So I know exactly what should be moved into a `to_delete` folder?

**Comment by e2d2** [comment]
Decided to move disk images into new folders.
