### ISSUE TITLE
.e0x file size in guymager output file

### ISSUE THREAD

**Issue by e2d2** [cul-it/rmc-workflow-scripts#16]
Instead of scraping the device size from guymager, let's grab the .e0x file size in bytes.

**Comment by dd388** [comment]
What if there are two e0x files? How should that be expressed?

**Comment by e2d2** [comment]
Add them together for a total.

**Comment by dd388** [comment]
organize-dirs.py now will sum up Exx file sizes. I tried it on a trivial example (i.e., I made up an E02 file of arbitrary size) but more rigorous testing should be done.

https://github.com/cul-it/rmc-workflow-scripts/commit/94ed81d5194c3e1bf397916d1cf96519b59bf7f9

**Comment by dd388** [comment]
We'll re-open if this is 1.) throwing errors or 2.) not reporting the right size. OK?
