### ISSUE TITLE
Write to output file for each iteration, rather than at the end

### ISSUE THREAD

**Issue by dd388** [cul-it/rmc-workflow-scripts#18]
This is so one error doesn't generate a completely empty output file

**Comment by dd388** [comment]
This seems to be ok in guymager script

**Comment by dd388** [comment]
Also seems to be okay in level1 data script

**Comment by dd388** [comment]
@e2d2 -- Can you let me know if you see an empty output file when you run the scripts? I can't remember which one is the culprit here.

**Comment by e2d2** [comment]
Have work around.
