### ISSUE TITLE
CSV files -- aggregate or separate for each script run?

### ISSUE THREAD

**Issue by dd388** [cul-it/rmc-workflow-scripts#3]
Should these scripts make an aggregate CSV file (with all of the metadata/information from each prior step) or make a new CSV file per script run? (And then you do the VLOOKUP magic?)

**Comment by e2d2** [comment]
At this point I'm going to say make a new CSV every time the script runs. I'll see how annoying that gets and let you know if it makes more sense to aggregate.

**Comment by dd388** [comment]
re-open if other format is needed
